/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiagnosticoPmmaIndexRouteImport } from './routes/diagnostico-pmma/index'
import { Route as DiagnosticoPmmaResultadoTokenRouteImport } from './routes/diagnostico-pmma/resultado/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoPmmaIndexRoute = DiagnosticoPmmaIndexRouteImport.update({
  id: '/diagnostico-pmma/',
  path: '/diagnostico-pmma/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoPmmaResultadoTokenRoute =
  DiagnosticoPmmaResultadoTokenRouteImport.update({
    id: '/diagnostico-pmma/resultado/$token',
    path: '/diagnostico-pmma/resultado/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico-pmma/': typeof DiagnosticoPmmaIndexRoute
  '/diagnostico-pmma/resultado/$token': typeof DiagnosticoPmmaResultadoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico-pmma': typeof DiagnosticoPmmaIndexRoute
  '/diagnostico-pmma/resultado/$token': typeof DiagnosticoPmmaResultadoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico-pmma/': typeof DiagnosticoPmmaIndexRoute
  '/diagnostico-pmma/resultado/$token': typeof DiagnosticoPmmaResultadoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/diagnostico-pmma/' | '/diagnostico-pmma/resultado/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/diagnostico-pmma' | '/diagnostico-pmma/resultado/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/diagnostico-pmma/'
    | '/diagnostico-pmma/resultado/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiagnosticoPmmaIndexRoute: typeof DiagnosticoPmmaIndexRoute
  DiagnosticoPmmaResultadoTokenRoute: typeof DiagnosticoPmmaResultadoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-pmma/': {
      id: '/diagnostico-pmma/'
      path: '/diagnostico-pmma'
      fullPath: '/diagnostico-pmma/'
      preLoaderRoute: typeof DiagnosticoPmmaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-pmma/resultado/$token': {
      id: '/diagnostico-pmma/resultado/$token'
      path: '/diagnostico-pmma/resultado/$token'
      fullPath: '/diagnostico-pmma/resultado/$token'
      preLoaderRoute: typeof DiagnosticoPmmaResultadoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiagnosticoPmmaIndexRoute: DiagnosticoPmmaIndexRoute,
  DiagnosticoPmmaResultadoTokenRoute: DiagnosticoPmmaResultadoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
