ALTER TABLE public.pmma_questions
  ADD COLUMN IF NOT EXISTS base_text text,
  ADD COLUMN IF NOT EXISTS version text NOT NULL DEFAULT 'PMMA-2026-v1',
  ADD COLUMN IF NOT EXISTS source_base text,
  ADD COLUMN IF NOT EXISTS revision_date date;

UPDATE public.pmma_questions SET is_active = false;

INSERT INTO public.pmma_questions (
  campaign_id, public_code, discipline, topic, base_text, statement, correct_answer,
  feedback_correct, feedback_wrong, key_point, difficulty, source_name, source_type,
  pedagogical_review_status, is_active, sort_order, version, source_base, revision_date
)
SELECT c.id, v.public_code, v.discipline, v.topic, v.base_text, v.statement, v.correct_answer,
       v.explanation, v.explanation, v.key_point, v.difficulty,
       'Edital360', 'autoral', 'aprovado', true, v.sort_order,
       'PMMA-2026-v1',
       'Conteúdo programático do concurso PMMA 2026 e simulado-base Edital360',
       CURRENT_DATE
FROM public.pmma_campaigns c
CROSS JOIN (VALUES
 ('PT01','Língua Portuguesa','Compreensão e interpretação de texto','Em operações de segurança pública, a rapidez da resposta não dispensa o planejamento. A tecnologia amplia a capacidade de comunicação, mas seu uso só produz resultados consistentes quando associado à formação continuada dos agentes. Por isso, equipamentos modernos, procedimentos claros e preparação profissional devem atuar de forma integrada.','De acordo com o texto, a rapidez da resposta torna desnecessário o planejamento das operações de segurança pública.',false,'O texto afirma exatamente o contrário: "a rapidez da resposta não dispensa o planejamento". Portanto, responder rapidamente não elimina a necessidade de planejar.','Em itens de interpretação, uma alteração de sentido como "não dispensa" para "torna desnecessário" invalida a afirmação.','facil',1),
 ('PT02','Língua Portuguesa','Conjunções e relações de sentido','Em operações de segurança pública, a rapidez da resposta não dispensa o planejamento. A tecnologia amplia a capacidade de comunicação, mas seu uso só produz resultados consistentes quando associado à formação continuada dos agentes. Por isso, equipamentos modernos, procedimentos claros e preparação profissional devem atuar de forma integrada.','No segundo período, a conjunção "mas" estabelece uma relação de oposição entre a ampliação da comunicação pela tecnologia e a necessidade de associá-la à formação continuada.',true,'A conjunção "mas" é adversativa e introduz uma ressalva: a tecnologia amplia a comunicação, porém esse benefício não basta isoladamente.','Conjunções adversativas introduzem contraste, oposição ou ressalva.','facil',2),
 ('PT03','Língua Portuguesa','Coesão referencial','Em operações de segurança pública, a rapidez da resposta não dispensa o planejamento. A tecnologia amplia a capacidade de comunicação, mas seu uso só produz resultados consistentes quando associado à formação continuada dos agentes. Por isso, equipamentos modernos, procedimentos claros e preparação profissional devem atuar de forma integrada.','Na expressão "mas seu uso", o pronome possessivo "seu" retoma a palavra "planejamento".',false,'O pronome "seu" retoma "a tecnologia". O sentido é: o uso da tecnologia só produz resultados consistentes quando associado à formação.','Para identificar o referente de um pronome, observe o termo anterior que mantém coerência semântica com a frase.','medio',3),
 ('PT04','Língua Portuguesa','Crase e regência','Em operações de segurança pública, a rapidez da resposta não dispensa o planejamento. A tecnologia amplia a capacidade de comunicação, mas seu uso só produz resultados consistentes quando associado à formação continuada dos agentes. Por isso, equipamentos modernos, procedimentos claros e preparação profissional devem atuar de forma integrada.','O emprego do sinal indicativo de crase em "associado à formação continuada" decorre da preposição exigida por "associado" somada ao artigo feminino que acompanha "formação".',true,'A construção "associado a" exige a preposição "a", e o substantivo feminino "formação" admite o artigo "a". A junção de preposição e artigo forma "à".','Crase = preposição "a" + artigo feminino "a".','medio',4),
 ('PT05','Língua Portuguesa','Pontuação','Em operações de segurança pública, a rapidez da resposta não dispensa o planejamento. A tecnologia amplia a capacidade de comunicação, mas seu uso só produz resultados consistentes quando associado à formação continuada dos agentes. Por isso, equipamentos modernos, procedimentos claros e preparação profissional devem atuar de forma integrada.','A retirada da vírgula imediatamente anterior à conjunção "mas" manteria a correção gramatical do segundo período.',false,'A vírgula deve separar as orações coordenadas ligadas pela conjunção adversativa "mas". Sua retirada prejudicaria a pontuação adequada do período.','Em regra, emprega-se vírgula antes de conjunções adversativas como "mas", "porém" e "contudo".','medio',5),

 ('HB01','História do Brasil','República Velha',NULL,'Na República Velha, a chamada Política dos Governadores estruturou uma relação de apoio entre o governo federal e as oligarquias estaduais.',true,'A Política dos Governadores consistiu em um pacto político pelo qual o governo federal apoiava as oligarquias estaduais, que, em troca, sustentavam o governo no Congresso.','A Política dos Governadores fortaleceu o domínio oligárquico durante a Primeira República.','facil',6),
 ('HB02','História do Brasil','Revolução de 1930',NULL,'A Revolução de 1930 depôs Washington Luís, impediu a posse de Júlio Prestes e levou Getúlio Vargas ao Governo Provisório.',true,'O movimento de 1930 encerrou a ordem política da República Velha, depôs Washington Luís e impediu a posse do presidente eleito Júlio Prestes, conduzindo Vargas ao poder.','1930 marcou a ruptura da política oligárquica da Primeira República.','facil',7),
 ('HB03','História do Brasil','Constituição de 1946',NULL,'A Constituição de 1946 consolidou o Estado Novo e ampliou os poderes autoritários concentrados no Poder Executivo.',false,'A Constituição de 1946 foi promulgada no contexto de redemocratização após o fim do Estado Novo. Ela restabeleceu instituições democráticas e garantias políticas.','Constituição de 1946 = redemocratização, e não continuidade do Estado Novo.','medio',8),
 ('HB04','História do Brasil','Governo Juscelino Kubitschek',NULL,'O Plano de Metas do governo Juscelino Kubitschek estimulou a industrialização e esteve associado à construção de Brasília.',true,'O Plano de Metas priorizou setores como energia, transporte, indústria e alimentação. Brasília foi apresentada como a meta-síntese do projeto desenvolvimentista.','JK ficou associado ao desenvolvimentismo e ao lema de acelerar o crescimento nacional.','facil',9),
 ('HB05','História do Brasil','Golpe de 1964',NULL,'O movimento político-militar de 1964 inaugurou um período de ampliação contínua das liberdades políticas e de fortalecimento da democracia representativa.',false,'O golpe de 1964 iniciou um regime autoritário, marcado por restrições políticas, atos institucionais, cassações e repressão.','O período iniciado em 1964 foi autoritário, e não de expansão democrática.','facil',10),

 ('HM01','História do Maranhão','França Equinocial',NULL,'A expedição francesa comandada por Daniel de La Touche chegou ao Maranhão em 1612 e esteve ligada à fundação de São Luís.',true,'Daniel de La Touche, Senhor de La Ravardière, liderou a expedição da França Equinocial que se estabeleceu na região em 1612 e fundou o núcleo de São Luís.','França Equinocial, Daniel de La Touche e fundação de São Luís são temas diretamente relacionados.','facil',11),
 ('HM02','História do Maranhão','Batalha de Guaxenduba',NULL,'A Batalha de Guaxenduba, ocorrida em 1614, terminou com a vitória francesa e consolidou definitivamente a França Equinocial.',false,'A batalha terminou com a vitória luso-portuguesa sobre os franceses e foi decisiva para o enfraquecimento da presença francesa no Maranhão.','Guaxenduba representou derrota francesa, não consolidação da França Equinocial.','facil',12),
 ('HM03','História do Maranhão','Revolta de Beckman',NULL,'A Revolta de Beckman esteve relacionada à insatisfação de proprietários com a Companhia de Comércio do Maranhão e com a atuação dos jesuítas na questão da mão de obra indígena.',true,'O movimento de 1684 reuniu descontentamentos contra o monopólio comercial e o fornecimento inadequado de mão de obra, além de conflitos com os jesuítas sobre a escravização indígena.','Revolta de Beckman = oposição ao monopólio comercial e conflito sobre mão de obra indígena.','medio',13),
 ('HM04','História do Maranhão','Adesão à Independência',NULL,'O Maranhão aderiu imediatamente à Independência do Brasil em setembro de 1822, sem resistência de grupos ligados a Portugal.',false,'A adesão maranhense não foi imediata. A província manteve fortes vínculos com Portugal e aderiu formalmente ao Império brasileiro apenas em 1823.','A adesão do Maranhão à Independência ocorreu de forma tardia e conflituosa.','medio',14),
 ('HM05','História do Maranhão','Balaiada',NULL,'A Balaiada foi um movimento popular ocorrido no Maranhão durante o período regencial, e sua repressão projetou militarmente Luís Alves de Lima e Silva.',true,'A Balaiada ocorreu entre 1838 e 1841, envolveu sertanejos, vaqueiros, artesãos e escravizados, e foi reprimida por forças comandadas por Luís Alves de Lima e Silva.','Balaiada = revolta regencial de caráter popular no Maranhão.','medio',15),

 ('GB01','Geografia do Brasil','Industrialização brasileira',NULL,'A concentração inicial da industrialização brasileira no Sudeste relacionou-se, entre outros fatores, à disponibilidade de capitais da economia cafeeira e à infraestrutura regional.',true,'A riqueza acumulada pelo café, a rede de transportes, o mercado consumidor e a disponibilidade de mão de obra favoreceram a concentração industrial no Sudeste.','Economia cafeeira e infraestrutura foram fatores importantes da concentração industrial.','medio',16),
 ('GB02','Geografia do Brasil','Urbanização',NULL,'Conurbação é o processo em que o crescimento urbano de municípios vizinhos provoca a continuidade física de suas áreas construídas.',true,'A conurbação ocorre quando manchas urbanas de cidades próximas se expandem até se unirem fisicamente.','Conurbação não significa fusão administrativa dos municípios, mas continuidade física da urbanização.','facil',17),
 ('GB03','Geografia do Brasil','Dinâmica demográfica',NULL,'A redução da fecundidade e o aumento da expectativa de vida contribuem para o envelhecimento da população brasileira.',true,'A queda no número médio de filhos e a maior longevidade alteram a estrutura etária, aumentando proporcionalmente a participação de idosos.','Menor fecundidade + maior longevidade = envelhecimento populacional.','facil',18),
 ('GB04','Geografia do Brasil','Transportes',NULL,'A matriz brasileira de transporte de cargas apresenta divisão equilibrada entre rodovias, ferrovias e hidrovias, sem predominância significativa de qualquer modal.',false,'O transporte rodoviário possui forte predominância na movimentação de cargas no Brasil, apesar da importância e da expansão de outros modais.','A matriz de transporte brasileira é historicamente marcada pela predominância rodoviária.','facil',19),
 ('GB05','Geografia do Brasil','Fronteiras agrícolas',NULL,'A região conhecida como MATOPIBA reúne áreas de Maranhão, Tocantins, Piauí e Bahia e se destaca pela expansão da agricultura mecanizada no Cerrado.',true,'O nome MATOPIBA deriva das iniciais dos quatro estados e identifica uma importante área de expansão da produção agrícola, especialmente de grãos.','MATOPIBA = Maranhão, Tocantins, Piauí e Bahia.','facil',20),

 ('GM01','Geografia do Maranhão','Localização e limites',NULL,'O Maranhão faz fronteira terrestre com Pará, Tocantins e Piauí.',true,'O estado limita-se com o Pará a oeste, o Tocantins ao sul e o Piauí a leste, além de possuir litoral voltado para o oceano Atlântico.','Os três estados limítrofes são Pará, Tocantins e Piauí.','facil',21),
 ('GM02','Geografia do Maranhão','Hidrografia',NULL,'O rio Itapecuru nasce no sul do Maranhão, percorre o território estadual e possui importância para o abastecimento da região de São Luís.',true,'O Itapecuru é um rio genuinamente maranhense e desempenha papel importante no abastecimento de água de municípios, incluindo a capital e sua região.','Itapecuru = rio maranhense de grande importância para o abastecimento.','medio',22),
 ('GM03','Geografia do Maranhão','Vegetação',NULL,'A Mata dos Cocais constitui uma faixa de transição vegetal e apresenta presença marcante de palmeiras como babaçu e carnaúba.',true,'A Mata dos Cocais funciona como área de transição entre diferentes domínios naturais, com destaque para palmeiras de importância econômica e social.','Mata dos Cocais = transição vegetal, babaçu e carnaúba.','facil',23),
 ('GM04','Geografia do Maranhão','Parques nacionais',NULL,'As lagoas sazonais dos Lençóis Maranhenses são alimentadas principalmente pelas chuvas acumuladas entre as dunas.',true,'As chuvas formam lagoas temporárias nas depressões entre as dunas, cuja quantidade e duração variam ao longo do ano.','Lençóis Maranhenses = dunas e lagoas sazonais alimentadas pelas chuvas.','facil',24),
 ('GM05','Geografia do Maranhão','Biomas',NULL,'O Parque Nacional da Chapada das Mesas localiza-se no sul do Maranhão e protege paisagens predominantemente pertencentes ao bioma Caatinga.',false,'A Chapada das Mesas está inserida predominantemente no bioma Cerrado, com chapadões, formações rochosas, rios e cachoeiras.','Chapada das Mesas = sul do Maranhão e bioma Cerrado.','medio',25),

 ('LP01','Legislação Pertinente à PMMA','Decreto nº 88.777/1983 — R-200',NULL,'Segundo o R-200, o policiamento ostensivo é identificado de relance pela farda, pelo equipamento ou pela viatura e tem por objetivo a manutenção da ordem pública.',true,'O regulamento caracteriza o policiamento ostensivo pela identificação imediata do policial ou da fração de tropa e por sua finalidade de manutenção da ordem pública.','Policiamento ostensivo envolve identificação visível e finalidade de manutenção da ordem pública.','medio',26),
 ('LP02','Legislação Pertinente à PMMA','Código Penal Militar',NULL,'Para o Código Penal Militar, considera-se praticado o crime no momento da ação ou da omissão, ainda que o resultado ocorra em momento diferente.',true,'O Código Penal Militar adota, quanto ao tempo do crime, a teoria da atividade: considera-se o momento da conduta, e não o momento do resultado.','Tempo do crime no CPM = momento da ação ou omissão.','medio',27),
 ('LP03','Legislação Pertinente à PMMA','Lei nº 14.751/2023',NULL,'A Lei Orgânica Nacional define as polícias militares como instituições temporárias, subordinadas diretamente ao Presidente da República e organizadas sem base hierárquica.',false,'A lei define as polícias militares como instituições militares permanentes, típicas de Estado, forças auxiliares e reserva do Exército, organizadas com base na hierarquia e na disciplina e subordinadas aos governadores.','PMs são instituições permanentes e organizadas com base na hierarquia e disciplina.','facil',28),
 ('LP04','Legislação Pertinente à PMMA','Lei nº 14.751/2023',NULL,'Conforme a Lei Orgânica Nacional, o comandante-geral deve ser escolhido entre oficiais da ativa do último posto do quadro previsto na própria lei.',true,'A Lei nº 14.751/2023 determina que o comandante-geral seja nomeado pelo governador entre oficiais da ativa do último posto do quadro correspondente.','Comandante-geral = oficial da ativa do último posto, nomeado pelo governador.','medio',29),
 ('LP05','Legislação Pertinente à PMMA','Lei Estadual nº 10.823/2018',NULL,'A Lei Estadual nº 10.823/2018 trata da criação e da transformação de organizações policiais militares da Polícia Militar do Maranhão.',true,'Esse é o objeto central da Lei Estadual nº 10.823/2018, indicada no conteúdo programático do concurso PMMA.','Lei nº 10.823/2018 = criação e transformação de organizações policiais militares.','facil',30),

 ('LI01','Legislação Institucional','Estatuto dos Policiais Militares do Maranhão',NULL,'A Lei Estadual nº 6.513/1995 regula a situação, as obrigações, os direitos, os deveres e as prerrogativas dos policiais militares do Maranhão.',true,'O artigo inicial do Estatuto estabelece exatamente esse campo de regulamentação.','Lei nº 6.513/1995 = Estatuto dos Policiais Militares do Maranhão.','facil',31),
 ('LI02','Legislação Institucional','Serviço policial-militar',NULL,'O serviço policial-militar compreende atividades inerentes à Polícia Militar relacionadas ao policiamento ostensivo e à preservação da ordem pública.',true,'O Estatuto relaciona o serviço policial-militar ao exercício das atividades próprias da instituição, incluindo o policiamento ostensivo e a preservação da ordem pública.','Serviço policial-militar está ligado às atividades finalísticas da corporação.','facil',32),
 ('LI03','Legislação Institucional','Carreira policial-militar',NULL,'A carreira policial-militar é privativa dos militares da ativa e se desenvolve conforme a sequência de graus hierárquicos.',true,'O Estatuto caracteriza a carreira como atividade contínua, privativa dos militares da ativa e organizada segundo os graus hierárquicos.','Carreira policial-militar = ativa, continuidade e hierarquia.','medio',33),
 ('LI04','Legislação Institucional','Situações do policial militar',NULL,'O componente da reserva remunerada, quando convocado, é considerado em situação de atividade.',true,'O Estatuto inclui entre os militares em atividade os componentes da reserva remunerada que tenham sido convocados.','Reserva remunerada convocada passa a integrar a situação de atividade durante a convocação.','medio',34),
 ('LI05','Legislação Institucional','Inatividade',NULL,'O policial militar reformado permanece sujeito à convocação ordinária para retornar ao serviço ativo sempre que houver necessidade administrativa.',false,'O reformado integra a inatividade e é dispensado definitivamente da prestação de serviço ativo, diferentemente do integrante da reserva remunerada sujeito às hipóteses legais de convocação.','Reserva remunerada e reforma são situações distintas dentro da inatividade.','medio',35),

 ('IN01','Noções de Informática','Sistemas de arquivos',NULL,'Em sistemas Linux, os nomes "relatorio.txt" e "Relatorio.txt" podem identificar arquivos diferentes no mesmo diretório.',true,'Sistemas de arquivos utilizados no Linux são normalmente sensíveis à diferença entre letras maiúsculas e minúsculas.','Linux é, em regra, case-sensitive.','facil',36),
 ('IN02','Noções de Informática','Planilhas eletrônicas',NULL,'Em uma planilha eletrônica, a referência $A$1 é absoluta tanto para a coluna quanto para a linha.',true,'Os dois sinais de cifrão fixam a coluna A e a linha 1, impedindo que a referência seja alterada quando a fórmula for copiada.','$A$1 = coluna absoluta e linha absoluta.','facil',37),
 ('IN03','Noções de Informática','Navegação privada',NULL,'O modo de navegação anônima impede que o provedor de internet e os sites acessados identifiquem o endereço IP do usuário.',false,'O modo anônimo reduz o armazenamento local de histórico, cookies e dados da sessão, mas não torna o usuário invisível para sites, redes corporativas ou provedores.','Navegação anônima não equivale a anonimato completo na internet.','facil',38),
 ('IN04','Noções de Informática','Correio eletrônico',NULL,'O protocolo SMTP é utilizado principalmente para o envio de mensagens de correio eletrônico.',true,'O SMTP é empregado no envio e na transferência de mensagens. Protocolos como IMAP e POP3 são tradicionalmente associados ao recebimento e acesso às caixas postais.','SMTP = envio; IMAP e POP3 = acesso ou recebimento.','facil',39),
 ('IN05','Noções de Informática','Segurança da informação',NULL,'Um worm depende obrigatoriamente de um arquivo hospedeiro e da execução manual desse arquivo para se espalhar por uma rede.',false,'O worm é um código malicioso capaz de se propagar automaticamente por redes. A dependência de arquivo hospedeiro é uma característica mais associada aos vírus.','Worm = propagação autônoma; vírus = associação a arquivo ou programa hospedeiro.','medio',40)
) AS v(public_code, discipline, topic, base_text, statement, correct_answer, explanation, key_point, difficulty, sort_order)
WHERE c.slug = 'simulado-pmma';

UPDATE public.pmma_campaigns
SET questions_per_attempt = 16,
    questions_per_discipline = 2,
    bonus_enabled = false,
    lead_capture_after_question = 4,
    updated_at = now()
WHERE slug = 'simulado-pmma';